In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Cargar el archivo CSV en un DataFrame
yutu = pd.read_csv('MXvideos_cc50_202101.csv')

In [3]:
yutu.head(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,state,lat,lon,geometry
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24.0,13/11/2017 1:06,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130.0,4182.0,361.0,1836.0,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,FALSO,FALSO,FALSO,Disfruta la presencia del Chef Torreblanca en ...,Tlaxcala,19.319995,-98.230010,POINT (-98.2300096 19.31999514)
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22.0,13/11/2017 0:11,La Voz Mexico 7,104972.0,271.0,174.0,369.0,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,FALSO,FALSO,FALSO,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Michoacan,19.679973,-100.569996,POINT (-100.569996 19.67997316)
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25.0,13/11/2017 12:00,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064.0,10105.0,266.0,607.0,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,FALSO,FALSO,FALSO,La canción del principio se llama “Este espíri...,Guerrero,17.549974,-99.500010,POINT (-99.5000096 17.54997398)
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25.0,12/11/2017 22:47,"temblor|""costa rica""|""sismo en costa rica""",96153.0,378.0,171.0,208.0,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,FALSO,FALSO,FALSO,El video es de un Walmart en el pais centroame...,Hidalgo,20.170434,-98.730031,POINT (-98.73003076000001 20.17043418)
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26.0,13/11/2017 14:17,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965.0,57781.0,681.0,7428.0,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,FALSO,FALSO,FALSO,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,Jalisco,19.770019,-104.369997,POINT (-104.3699966 19.77001935)

In [4]:
yutu.describe()

,category_id,views,likes,dislikes,comment_count,lat,lon
count,40451.000000,4.045100e+04,4.045100e+04,4.045100e+04,40451.000000,44043.000000,44043.000000
mean,21.003140,3.423820e+05,1.586184e+04,7.471604e+02,2039.660008,21.481515,-100.242120
std,5.878995,1.714691e+06,8.108987e+04,1.095358e+04,13938.031797,3.502304,6.018379
min,1.000000,1.570000e+02,0.000000e+00,0.000000e+00,0.000000,16.429991,-116.009260
25%,20.000000,1.681300e+04,2.990000e+02,1.700000e+01,42.000000,18.920381,-103.500024
50%,24.000000,5.697300e+04,1.246000e+03,6.300000e+01,196.000000,20.379982,-99.669999
75%,24.000000,2.068940e+05,7.226000e+03,2.670000e+02,885.000000,22.733353,-98.230010
max,43.000000,1.009124e+08,4.470923e+06,1.353667e+06,905925.000000,30.764051,-86.711455

In [5]:
# Verificar qué columnas tienen datos faltantes y cuántos hay en cada una
datos_faltantes = yutu.isnull().sum()
print(datos_faltantes)

video_id                    84
trending_date             3450
title                     3533
channel_title             3542
category_id               3592
publish_time              3592
tags                      3563
views                     3592
likes                     3592
dislikes                  3592
comment_count             3592
thumbnail_link            3572
comments_disabled         3592
ratings_disabled          3592
video_error_or_removed    3592
description               7797
state                        0
lat                          0
lon                          0
geometry                     0
dtype: int64

In [6]:
# Eliminar filas con datos faltantes en columnas críticas
yutu.dropna(subset=['video_id'], inplace=True)

In [7]:
# Convertir las columnas necesarias a los tipos adecuados
yutu['trending_date'] = pd.to_datetime(yutu['trending_date'], format='%y.%d.%m', errors='coerce')
yutu['publish_time'] = pd.to_datetime(yutu['publish_time'], errors='coerce')

# Convertir columnas numéricas
numerical_cols = ['views', 'likes', 'dislikes', 'comment_count', 'category_id', 'lat', 'lon']
for col in numerical_cols:
    yutu[col] = pd.to_numeric(yutu[col], errors='coerce')

# Eliminar filas con fechas no válidas
yutu = yutu.dropna(subset=['trending_date', 'publish_time'])

# Reemplazar valores faltantes en columnas categóricas con la moda
yutu['description'].fillna(yutu['description'].mode()[0], inplace=True)

C:\Users\aaron\AppData\Local\Temp\ipykernel_10812\3258165731.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  yutu['publish_time'] = pd.to_datetime(yutu['publish_time'], errors='coerce')
C:\Users\aaron\AppData\Local\Temp\ipykernel_10812\3258165731.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  yutu['description'].fillna(yutu['description'].mode()[0], inplace=True)

In [8]:
yutu.isnull().sum()

video_id                  0
trending_date             0
title                     0
channel_title             0
category_id               0
publish_time              0
tags                      0
views                     0
likes                     0
dislikes                  0
comment_count             0
thumbnail_link            0
comments_disabled         0
ratings_disabled          0
video_error_or_removed    0
description               0
state                     0
lat                       0
lon                       0
geometry                  0
dtype: int64

In [9]:
# Guardar el DataFrame limpio en un nuevo archivo CSV
yutu.to_csv('Datos_Limpios.csv', index=False)